const projects = [
  {
    name: 'I am Lawrence',
    date: 'March 2016 - Now',
    text: 'My Portfolio and Resume',
    tech: ['ExpressJS', 'ReactJS', 'es6', 'JavaScript'],
    link: 'http://lawry.io',
    github: 'https://github.com/lorix-lpan/im-lawrence',
  },
  {
    name: 'Find a Classroom',
    date: 'March 2016 - Now',
    text: 'A smart Web App that tells you which classrooms are free at a given moment.',
    tech: ['ExpressJS', 'MongoDB', 'ReactJS', 'es6', 'JavaScript'],
    github: 'https://github.com/lorix-lpan/find-a-classroom',
  },
  {
    name: 'Potential Wheel',
    date: 'March 2016',
    text: 'A browser controlled robot with funky locomotion. Built at Robohacks.',
    tech: ['Socket.io', 'ReactJS', 'es6', 'JavaScript', 'Arduino', 'Raspberry Pi'],
    link: 'http://devpost.com/software/potential-wheel',
    github: 'https://github.com/lorix-lpan/potential-wheel',
  },
  {
    name: 'Talky Johnny',
    date: 'March 2016',
    text: 'Boilerplate code for browser-controlled Node.js Robots',
    tech: ['ExpressJS', 'Socket.io', 'Johnny Five', 'ReactJS', 'es6', 'JavaScript'],
    github: 'https://github.com/lorix-lpan/talky-johnny',
  },
  {
    name: 'Perfect Schedule',
    date: 'February 2016 - Now',
    text: 'Perfect Schedule is a non-profit Startup that helps students to build the best schedule possible',
    tech: ['ReactJS', 'Redux', 'ExpressJS', 'MongoDB', 'es6', 'JavaScript'],
    link: 'http://schedule-perfect.me',
    github: 'https://github.com/lorix-lpan/perfect-schedule',
  },
  {
    name: 'Marianopolis Course Offering PDF Converter',
    date: 'February 2016',
    text: 'A program that converts the Marianopolis course offering PDF into JSON format',
    tech: ['es6', 'JavaScript'],
    github: 'https://github.com/lorix-lpan/converter-marianopolis',
  },
  {
    name: 'Food Slayer',
    date: 'February 2016',
    text: 'A Backendless Angular App that reads a picture of raw ingredients and returns a list of recipes. Built at ConUHacks',
    tech: ['AngularJS', 'JSONP', 'es5', 'JavaScript'],
    github: 'https://github.com/lorix-lpan/food-slayr',
  },
  {
    name: 'Canadian Robotics Competition 2016',
    date: 'December 2015 - February 2016',
    text: 'Website built for Marianopolis Robotics 2016. It came in first in the Canadian Robotics Competition Web Design Contest',
    tech: ['AngularJS', 'jQuery', 'es5', 'Javascript', 'Gulp'],
    link: 'http://robotics.marianopolis.edu',
    github: 'https://github.com/lorix-lpan/marianopolis-robotics-2016',
  },
  {
    name: 'R Score Calculator',
    date: 'December 2015',
    text: 'A better R Score Calculator with smooth transition and Material Design.',
    tech: ['AngularJS', 'Angular Material', 'es5', 'Javascript', 'Gulp'],
    link: 'http://www.myrscore.com',
    github: 'https://github.com/lorix-lpan/rscore-learner',
  },
  {
    name: 'Resolve Them',
    date: 'November 2015',
    text: 'A configurable and platform-independent Shellscript that helps to resolve the dependencies of your program',
    tech: ['Bash', 'Linux'],
    github: 'https://github.com/lorix-lpan/resolve-them',
  },
  {
    name: 'Allele Fixation Simulator',
    date: 'November 2015',
    text: 'A Python program with GUI that simulates the process of allele fixation. Built for Enriched Biology I',
    tech: ['Python3', 'PyQt5', 'Bash'],
    github: 'https://github.com/lorix-lpan/alleles-fixation',
  },
  {
    name: 'Desktop Config',
    date: 'July 2015 - Now',
    text: 'A Desktop Configuration Manager that keeps my configuration files in sync across multiple devices',
    tech: ['Bash'],
    github: 'https://github.com/lorix-lpan/ccc_helper',
  },
  {
    name: 'CCC-Helper',
    date: 'July 2015',
    text: 'A bash program written with the purpose of organizing my CCC practice files',
    tech: ['Bash'],
    github: 'https://github.com/lorix-lpan/ccc_helper',
  },
  {
    name: 'Yaourt Installer',
    date: 'June 2015',
    text: 'A bash Yaourt installer with automatic dependency resolution',
    tech: ['Bash', 'Arch Linux'],
    github: 'https://github.com/lorix-lpan/yaourt-installer',
  },
];

export default projects;
